In [1]:
from dhdbscan.HDBSCAN import HDBSCAN

# Probleme mit HDBSCAN

## Mutual Reachability Matrix

In der Hdbscan Implementierung wird die Mutual Reachability effizient über eine Matrix operation berechnet. 


"""
size = distance_matrix.shape[0]
min_points = min(size - 1, min_points)
try:
    core_distances = np.partition(distance_matrix,
                                  min_points,
                                  axis=0)[min_points]
except AttributeError:
    core_distances = np.sort(distance_matrix,
                             axis=0)[min_points]

if alpha != 1.0:
    distance_matrix = distance_matrix / alpha

stage1 = np.where(core_distances > distance_matrix,
                  core_distances, distance_matrix)
result = np.where(core_distances > stage1.T,
                  core_distances.T, stage1.T).T
return result"""

Input ist eine distanz matrix. Np.partition sortiert dann die distanz matrix. Das heißt alle core distanzen pro datenpunkt werden abgegriffen. Grundsätzlich sollte die Mutual reachability matrix symmetrisch sein. Es stellt sich jedoch heraus, dass dies nicht der Fall ist.



In [53]:
dataset = np.load('clusterable_data.npy')
clusterer = HDBSCAN(min_points=15)
clusterer.fit(dataset)
clusterer

Iteration: 0
Distance matrix is symmetric: False
Mutual reachability matrix is symmetric: False

Iteration: 1
Distance matrix is symmetric: False
Mutual reachability matrix is symmetric: False

Iteration: 2
Distance matrix is symmetric: False
Mutual reachability matrix is symmetric: False


## Dendogram Linkage Matrix
Die dendogram linakge matrix is zudem nicht deterministisch.

$\begin{tikzpicture}
[
    level 1/.style={sibling distance=25mm}
]
	\node {Root Node}
		child {node {Left Child}}
		child {node {Right Child}};
\end{tikzpicture}$

## 

Dataset:
[[0.  1.  0.1]
 [3.  2.  0.2]
 [1.  2.  0.2]
 [3.  4.  0.3]]
Single_linkage_tree:
[[0.  1.  0.1 2. ]
 [3.  2.  0.2 2. ]
 [5.  6.  0.2 4. ]
 [7.  4.  0.3 5. ]]
Labels: [ 0  0  1  1 -1]


Dataset:
[[0.  1.  0.1]
 [1.  2.  0.2]
 [3.  2.  0.2]
 [3.  4.  0.3]]
Single_linkage_tree:
[[0.  1.  0.1 2. ]
 [5.  2.  0.2 3. ]
 [3.  6.  0.2 4. ]
 [7.  4.  0.3 5. ]]
Labels: [-1 -1 -1 -1 -1]


'dataset = np.array([[0,0],[0,0.1],[0,0.3],[0.2,0.3],[0.2,0.6]])\n\nfor i in range(3):\n    np.random.seed(42)\n    shuffled_indices = np.random.permutation(len(dataset))\n    shuffled_data = dataset[shuffled_indices]\n    clusterer = HDBSCAN(min_points=2)\n    clusterer.fit_hdbscan(shuffled_data)\n    print("Dataset:")\n    print(dataset)\n    print("Single_linkage_tree:")\n    print(clusterer.single_linkage_tree)\n    print("Labels:", clusterer.labels_)\n    print("\n")'

# Vergleich Implementierungen